### ISSUE TITLE
Lua couldn't be found with C-101CC

### ISSUE THREAD

**Issue by flappiefh** [zedroopy/DCS_Radio_Mission_Mod#3]
The mission uses OPFOR C-101CC and EB. But when I first added those, they were blue. I then changed their country to Russia, then tried to launch the app.

[Flappie_Chemical bromance_test_SRS.zip](https://github.com/zedroopy/DCS_Radio_Mission_Mod/files/4471446/Flappie_Chemical.bromance_test_SRS.zip)
"Choose side (coalition) on which you'd like to apply the presets template:
        - Blue: type 'b'
        - Red: type 'r'
b
[...]

¤¤¤¤¤ C-101CC ¤¤¤¤¤
Node/Lua couldn't be found. Aborting. x_X
Press any key to exit this window..."

**Comment by zedroopy** [comment]
flawed aircraft seeking logic. FIXED.
