### ISSUE TITLE
VHF_AM_RADIO\SETTINGS.lua not found

### ISSUE THREAD

**Issue by flappiefh** [zedroopy/DCS_Radio_Mission_Mod#4]
This error message appears at the end of the log, when I give the attached MIZ file to the RC4 and that I choose the **red** side:

> Impossible de trouver une partie du chemin d'accès 'C:\Users\Flav\Desktop\VHF_AM_RADIO\SETTINGS.lua'.
> Aborting. x_X
> 
> Press any key to exit this window...

Also, it says "aborting" but the app DOES modify the file.

I don't get any error message when I choose the blue side.

[Flappie_Chemical bromance_test_SRS.zip](https://github.com/zedroopy/DCS_Radio_Mission_Mod/files/4473765/Flappie_Chemical.bromance_test_SRS.zip)

**Comment by zedroopy** [comment]
Ok, it aborted during the specific A-10 logic, which takes place after the mission file modifications.
The mission file should be modified with proper presets though, it's still valid.
The A-10C logic was missing an existing file check. Fixed.
ALso I had more feedback about the final steps process, so you'll know when it really aborted and what changed in the file.
