### ISSUE TITLE
RC5 JF-17 "Node\Lua" not found

### ISSUE THREAD

**Issue by flappiefh** [zedroopy/DCS_Radio_Mission_Mod#5]
Here's a small bug encountered with another mission (MIZ attached). It happens when choosing the **red** side. It seems related to an hypothetic third JF-17 radio.

> [...]
> no F-14B unit found.
> 
> no F-16C_50 unit found.
> 
> ¤¤¤¤¤ JF-17 #1 ¤¤¤¤¤
> |  COM 1/2  |
> 
> ¤¤¤¤¤ JF-17 #2 ¤¤¤¤¤
> |  COM 1/2  |
> 
> ¤¤¤¤¤ JF-17 #3 ¤¤¤¤¤
> |  Node/Lua couldn't be found. Aborting. x_X
> 
> Press any key to exit this window...

[Flappie_Chicken_Valley.zip](https://github.com/zedroopy/DCS_Radio_Mission_Mod/files/4475096/Flappie_Chicken_Valley.zip)

**Comment by zedroopy** [comment]
IA JF-17 don't have Radio presets. Parser wasn't looking for Clients only. Fixed.
