### ISSUE TITLE
RC6 - AI-only sides take much more time to complete

### ISSUE THREAD

**Issue by flappiefh** [zedroopy/DCS_Radio_Mission_Mod#6]
Let's say a mission has 24 blue client flights and 0 red client flights: it will be way longer to treat the red side, where it should be the opposite.

Two missions are attached: one with only blue clients, and a copy with one red client added.

[Flappie_Caviar_sandwich_v2_test.zip](https://github.com/zedroopy/DCS_Radio_Mission_Mod/files/4476693/Flappie_Caviar_sandwich_v2_test.zip)

**Comment by zedroopy** [comment]
Fixed in RC7
