### ISSUE TITLE
Modulations get replaced instead of channels

### ISSUE THREAD

**Issue by flappiefh** [zedroopy/DCS_Radio_Mission_Mod#7]
When giving the attached MIZ file to the RC6 app, the following aircraft radio "modulations" get modified instead of the "channels":

- M-2000C (radio 2 only)
- AV-8B NA (radio 2 and 3)
- F-14B (radio 2 only)
- F-16C (radio 2 only)
- F/A-18C (radio 2 only)

To sum it up, only the channels of an aircraft first radio get modified properly.

[Soutient au troupes Sud Minab F16 Bl50 Hard.zip](https://github.com/zedroopy/DCS_Radio_Mission_Mod/files/4514305/Soutient.au.troupes.Sud.Minab.F16.Bl50.Hard.zip)

**Comment by zedroopy** [comment]
Fixed in RC8
